.TH "GCLOUD AUTH REVOKE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_auth_revoke \- revoke authorization for credentials
.SH "SYNOPSIS"
.sp
gcloud auth revoke [\fIACCOUNTS\fR \&...] [\fB\-\-all\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
Revoke credentials\&. If no account is provided, the currently active account is used\&.
.SH "POSITIONAL ARGUMENTS"
.HP
[\fIACCOUNTS\fR \&...]
.RE
.SH "FLAGS"
.PP
\fB\-\-all\fR
.RS 4
Revoke all known credentials\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcore\fR component\&. See installing components if it is not installed\&.
