.TH "GCLOUD AUTH ACTIVATE-SERVICE-ACCOUNT" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_auth_activate-service-account \- get credentials via the private key for a service account
.SH "SYNOPSIS"
.sp
gcloud auth activate\-service\-account [\fIACCOUNT\fR] \fB\-\-key\-file\fR \fIKEY_FILE\fR [\fB\-\-password\-file\fR \fIPASSWORD_FILE\fR | \fB\-\-prompt\-for\-password\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
Get credentials for a service account, using a \&.json file or a \&.p12 file for the private key\&. Password is only applicable for \&.p12 file\&. If \-\-project is set, set the default project\&.
.SH "POSITIONAL ARGUMENTS"
.HP
[\fIACCOUNT\fR]
.RE
.SH "FLAGS"
.PP
\fB\-\-key\-file\fR \fIKEY_FILE\fR
.RS 4
Path to the service accounts private key\&.
.RE
.PP
\fB\-\-password\-file\fR \fIPASSWORD_FILE\fR
.RS 4
Path to a file containing the password for the service account private key (only for \&.p12 file)\&.
.RE
.PP
\fB\-\-prompt\-for\-password\fR
.RS 4
Prompt for the password for the service account private key (only for \&.p12 file)\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcore\fR component\&. See installing components if it is not installed\&.
