.TH "GCLOUD COMPONENTS REPOSITORIES ADD" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_components_repositories_add \- add a new Trusted Tester component repository
.SH "SYNOPSIS"
.sp
gcloud components repositories add \fIURL\fR [\fIURL\fR \&...] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
Add a new Trusted Tester component repository to the list of repositories used by the component manager\&. This will allow you to install and update components found in this repository\&.
.sp
If you are participating in a Trusted Tester program, you will be instructed on the location of repositories with additional versions of one or more Cloud SDK components\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIURL\fR [\fIURL\fR \&...]
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "EXAMPLES"
.sp
To add the Trusted Tester component repository http://repo\&.location\&.com run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud components repositories add http://repo\&.location\&.com
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcore\fR component\&. See installing components if it is not installed\&.
