.TH "GCLOUD AUTH" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_auth \- manage oauth2 credentials for the Google Cloud SDK
.SH "SYNOPSIS"
.sp
gcloud auth \fICOMMAND\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
Manage oauth2 credentials for the Google Cloud SDK\&.
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.HP
\fBactivate\-refresh\-token\fR
.RE
.PP
\fBactivate\-service\-account\fR
.RS 4
Get credentials via the private key for a service account\&.
.RE
.PP
\fBlist\fR
.RS 4
List the accounts for known credentials\&.
.RE
.PP
\fBlogin\fR
.RS 4
Get credentials for the tools in the Google Cloud SDK via a web flow\&.
.RE
.PP
\fBrevoke\fR
.RS 4
Revoke authorization for credentials\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcore\fR component\&. See installing components if it is not installed\&.
