.TH "GCLOUD AUTH GIT-HELPER" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_auth_git-helper \- a git credential helper to provide access to Google git repositories
.SH "SYNOPSIS"
.sp
gcloud auth git\-helper \fIMETHOD\fR [\fB\-\-ignore\-unknown\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
A git credential helper to provide access to Google git repositories\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIMETHOD\fR
.RE
.SH "FLAGS"
.PP
\fB\-\-ignore\-unknown\fR
.RS 4
Produce no output and exit with 0 when given an unknown method (e\&.g\&. store) or host\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcore\fR component\&. See installing components if it is not installed\&.
.sp
This command is an internal implementation detail and may change or disappear without notice\&.
