.TH "GCLOUD AUTH ACTIVATE-REFRESH-TOKEN" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_auth_activate-refresh-token \- get credentials via an existing refresh token
.SH "SYNOPSIS"
.sp
gcloud auth activate\-refresh\-token \fIACCOUNT\fR [\fITOKEN\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
Use an oauth2 refresh token to manufacture credentials for Google APIs\&. This token must have been acquired via some legitimate means to work\&. The account provided is only used locally to help the Cloud SDK keep track of the new credentials, so you can activate, list, and revoke the credentials in the future\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIACCOUNT\fR
.RE
.PP
[\fITOKEN\fR]
.RS 4
OAuth2 refresh token\&. If blank, prompt for value\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcore\fR component\&. See installing components if it is not installed\&.
