.TH "GCLOUD CONFIG LIST" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_config_list \- view Google Cloud SDK properties
.SH "SYNOPSIS"
.sp
gcloud config list [\fISECTION\fR/\fIPROPERTY\fR] [\fB\-\-all\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
List all currently available Cloud SDK properties associated with your current workspace or global configuration\&.
.SH "POSITIONAL ARGUMENTS"
.HP
[\fISECTION\fR/\fIPROPERTY\fR]
.RE
.SH "FLAGS"
.PP
\fB\-\-all\fR
.RS 4
List all set and unset properties that match the arguments\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "EXAMPLES"
.sp
To list the project property in the core section, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud config list project
.fi
.if n \{\
.RE
.\}
.sp
To list the zone property in the compute section, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud config list compute/zone
.fi
.if n \{\
.RE
.\}
.sp
To list all the properties, run: $ gcloud config list \-\-all
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcore\fR component\&. See installing components if it is not installed\&.
