.TH "GCLOUD INIT" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_init \- create and initialize a gcloud workspace in the current directory
.SH "SYNOPSIS"
.sp
gcloud init \fIPROJECT\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
This command creates and initializes a local workspace for a Google Cloud Platform project\&.
.sp
The local workspace is indicated by the creation of a [\&.gcloud] folder\&. In this folder is a file [properties] which allows you to override any global properties you may have set via the $ gcloud config command\&.
.sp
When you run a Cloud SDK command\-line tool from within this new workspace, it will use the new [properties] file as the first place to load properties\&. As a result, if you use gcloud, gcutil, gsutil, or any of the other commands in google\-cloud\-sdk/bin from within the workspace, they will connect to the correct project\&.
.sp
If you have enabled push\-to\-deploy in the Cloud Console, one of the things that gcloud init will do for you is cloning the Google\-hosted git repository associated with PROJECT\&. This repository will automatically be connected to Google, and it will use the credentials indicated as \fIactive\fR by gcloud auth list\&. Pushing to the origin\(cqs \fImaster\fR branch will trigger an App Engine deployment using the contents of that branch\&.
.sp
**Note: this command will be changing soon\&. Consider using $ gcloud alpha source clone to clone authenticated git repository\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIPROJECT\fR
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "EXAMPLES"
.sp
To perform a simple "Hello, world!" App Engine deployment with this command, run the following command lines with MYPROJECT replaced by a project you own and can use for this experiment\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud auth login
$ gcloud init MYPROJECT
$ cd MYPROJECT/default
$ git pull
  https://github\&.com/GoogleCloudPlatform/appengine\-helloworld\-python
$ git push origin master
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcore\fR component\&. See installing components if it is not installed\&.
