.TH "GCLOUD COMPONENTS LIST" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_components_list \- list the status of all Cloud SDK components
.SH "SYNOPSIS"
.sp
gcloud components list [\fB\-\-show\-versions\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
This command lists all the tools in the Cloud SDK (both individual components and preconfigured packages of components)\&. For each component, the command lists the following information:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Status on your local workstation: not installed, installed (and up to date), and update available (installed, but not up to date)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Name of the component (a description)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ID of the component (used to refer to the component in other [gcloud components] commands)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Size of the component
.RE
.sp
In addition, if the \-\-show\-versions flag is specified, the command lists the currently installed version (if any) and the latest available version of each individual component\&.
.SH "FLAGS"
.HP
\fB\-\-show\-versions\fR
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "EXAMPLES"
.sp
$ gcloud components list
.sp
$ gcloud components list \-\-show\-versions
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcore\fR component\&. See installing components if it is not installed\&.
