"""Generated message classes for dataflow version v1b3.

Google Dataflow API.
"""
# NOTE: This file is autogenerated and should not be edited by hand.

from protorpc import messages as _messages

from googlecloudapis.apitools.base.py import encoding
from googlecloudapis.apitools.base.py import extra_types


package = 'dataflow'


class ApproximateProgress(_messages.Message):
  """A ApproximateProgress object.

  Fields:
    percentComplete: A number attribute.
    position: A Position attribute.
    remainingTime: A string attribute.
  """

  percentComplete = _messages.FloatField(1, variant=_messages.Variant.FLOAT)
  position = _messages.MessageField('Position', 2)
  remainingTime = _messages.StringField(3)


class AutoscalingSettings(_messages.Message):
  """A AutoscalingSettings object.

  Enums:
    AlgorithmValueValuesEnum:

  Fields:
    algorithm: A AlgorithmValueValuesEnum attribute.
    maxNumWorkers: A integer attribute.
  """

  class AlgorithmValueValuesEnum(_messages.Enum):
    """AlgorithmValueValuesEnum enum type.

    Values:
      AUTOSCALING_ALGORITHM_BASIC: <no description>
      AUTOSCALING_ALGORITHM_NONE: <no description>
      AUTOSCALING_ALGORITHM_UNKNOWN: <no description>
    """
    AUTOSCALING_ALGORITHM_BASIC = 0
    AUTOSCALING_ALGORITHM_NONE = 1
    AUTOSCALING_ALGORITHM_UNKNOWN = 2

  algorithm = _messages.EnumField('AlgorithmValueValuesEnum', 1)
  maxNumWorkers = _messages.IntegerField(2, variant=_messages.Variant.INT32)


class ComputationTopology(_messages.Message):
  """A ComputationTopology object.

  Fields:
    computationId: A string attribute.
    inputs: A StreamLocation attribute.
    keyRanges: A KeyRangeLocation attribute.
    outputs: A StreamLocation attribute.
  """

  computationId = _messages.StringField(1)
  inputs = _messages.MessageField('StreamLocation', 2, repeated=True)
  keyRanges = _messages.MessageField('KeyRangeLocation', 3, repeated=True)
  outputs = _messages.MessageField('StreamLocation', 4, repeated=True)


class CustomSourceLocation(_messages.Message):
  """A CustomSourceLocation object.

  Fields:
    stateful: A boolean attribute.
  """

  stateful = _messages.BooleanField(1)


class DataDiskAssignment(_messages.Message):
  """A DataDiskAssignment object.

  Fields:
    dataDisks: A string attribute.
    vmInstance: A string attribute.
  """

  dataDisks = _messages.StringField(1, repeated=True)
  vmInstance = _messages.StringField(2)


class DataflowProjectsJobsCreateRequest(_messages.Message):
  """A DataflowProjectsJobsCreateRequest object.

  Enums:
    ViewValueValuesEnum:

  Fields:
    job: A Job resource to be passed as the request body.
    projectId: A string attribute.
    replaceJobId: A string attribute.
    view: A ViewValueValuesEnum attribute.
  """

  class ViewValueValuesEnum(_messages.Enum):
    """ViewValueValuesEnum enum type.

    Values:
      JOB_VIEW_ALL: <no description>
      JOB_VIEW_SUMMARY: <no description>
      JOB_VIEW_UNKNOWN: <no description>
    """
    JOB_VIEW_ALL = 0
    JOB_VIEW_SUMMARY = 1
    JOB_VIEW_UNKNOWN = 2

  job = _messages.MessageField('Job', 1)
  projectId = _messages.StringField(2, required=True)
  replaceJobId = _messages.StringField(3)
  view = _messages.EnumField('ViewValueValuesEnum', 4)


class DataflowProjectsJobsGetMetricsRequest(_messages.Message):
  """A DataflowProjectsJobsGetMetricsRequest object.

  Fields:
    jobId: A string attribute.
    projectId: A string attribute.
    startTime: A string attribute.
  """

  jobId = _messages.StringField(1, required=True)
  projectId = _messages.StringField(2, required=True)
  startTime = _messages.StringField(3)


class DataflowProjectsJobsGetRequest(_messages.Message):
  """A DataflowProjectsJobsGetRequest object.

  Enums:
    ViewValueValuesEnum:

  Fields:
    jobId: A string attribute.
    projectId: A string attribute.
    view: A ViewValueValuesEnum attribute.
  """

  class ViewValueValuesEnum(_messages.Enum):
    """ViewValueValuesEnum enum type.

    Values:
      JOB_VIEW_ALL: <no description>
      JOB_VIEW_SUMMARY: <no description>
      JOB_VIEW_UNKNOWN: <no description>
    """
    JOB_VIEW_ALL = 0
    JOB_VIEW_SUMMARY = 1
    JOB_VIEW_UNKNOWN = 2

  jobId = _messages.StringField(1, required=True)
  projectId = _messages.StringField(2, required=True)
  view = _messages.EnumField('ViewValueValuesEnum', 3)


class DataflowProjectsJobsListRequest(_messages.Message):
  """A DataflowProjectsJobsListRequest object.

  Enums:
    ViewValueValuesEnum:

  Fields:
    pageSize: A integer attribute.
    pageToken: A string attribute.
    projectId: A string attribute.
    view: A ViewValueValuesEnum attribute.
  """

  class ViewValueValuesEnum(_messages.Enum):
    """ViewValueValuesEnum enum type.

    Values:
      JOB_VIEW_ALL: <no description>
      JOB_VIEW_SUMMARY: <no description>
      JOB_VIEW_UNKNOWN: <no description>
    """
    JOB_VIEW_ALL = 0
    JOB_VIEW_SUMMARY = 1
    JOB_VIEW_UNKNOWN = 2

  pageSize = _messages.IntegerField(1, variant=_messages.Variant.INT32)
  pageToken = _messages.StringField(2)
  projectId = _messages.StringField(3, required=True)
  view = _messages.EnumField('ViewValueValuesEnum', 4)


class DataflowProjectsJobsMessagesListRequest(_messages.Message):
  """A DataflowProjectsJobsMessagesListRequest object.

  Enums:
    MinimumImportanceValueValuesEnum:

  Fields:
    endTime: A string attribute.
    jobId: A string attribute.
    minimumImportance: A MinimumImportanceValueValuesEnum attribute.
    pageSize: A integer attribute.
    pageToken: A string attribute.
    projectId: A string attribute.
    startTime: A string attribute.
  """

  class MinimumImportanceValueValuesEnum(_messages.Enum):
    """MinimumImportanceValueValuesEnum enum type.

    Values:
      JOB_MESSAGE_BASIC: <no description>
      JOB_MESSAGE_DEBUG: <no description>
      JOB_MESSAGE_DETAILED: <no description>
      JOB_MESSAGE_ERROR: <no description>
      JOB_MESSAGE_IMPORTANCE_UNKNOWN: <no description>
      JOB_MESSAGE_WARNING: <no description>
    """
    JOB_MESSAGE_BASIC = 0
    JOB_MESSAGE_DEBUG = 1
    JOB_MESSAGE_DETAILED = 2
    JOB_MESSAGE_ERROR = 3
    JOB_MESSAGE_IMPORTANCE_UNKNOWN = 4
    JOB_MESSAGE_WARNING = 5

  endTime = _messages.StringField(1)
  jobId = _messages.StringField(2, required=True)
  minimumImportance = _messages.EnumField('MinimumImportanceValueValuesEnum', 3)
  pageSize = _messages.IntegerField(4, variant=_messages.Variant.INT32)
  pageToken = _messages.StringField(5)
  projectId = _messages.StringField(6, required=True)
  startTime = _messages.StringField(7)


class DataflowProjectsJobsPatchRequest(_messages.Message):
  """A DataflowProjectsJobsPatchRequest object.

  Fields:
    job: A Job resource to be passed as the request body.
    jobId: A string attribute.
    projectId: A string attribute.
  """

  job = _messages.MessageField('Job', 1)
  jobId = _messages.StringField(2, required=True)
  projectId = _messages.StringField(3, required=True)


class DataflowProjectsJobsUpdateRequest(_messages.Message):
  """A DataflowProjectsJobsUpdateRequest object.

  Fields:
    job: A Job resource to be passed as the request body.
    jobId: A string attribute.
    projectId: A string attribute.
  """

  job = _messages.MessageField('Job', 1)
  jobId = _messages.StringField(2, required=True)
  projectId = _messages.StringField(3, required=True)


class DataflowProjectsJobsWorkItemsLeaseRequest(_messages.Message):
  """A DataflowProjectsJobsWorkItemsLeaseRequest object.

  Fields:
    jobId: A string attribute.
    leaseWorkItemRequest: A LeaseWorkItemRequest resource to be passed as the
      request body.
    projectId: A string attribute.
  """

  jobId = _messages.StringField(1, required=True)
  leaseWorkItemRequest = _messages.MessageField('LeaseWorkItemRequest', 2)
  projectId = _messages.StringField(3, required=True)


class DataflowProjectsJobsWorkItemsReportStatusRequest(_messages.Message):
  """A DataflowProjectsJobsWorkItemsReportStatusRequest object.

  Fields:
    jobId: A string attribute.
    projectId: A string attribute.
    reportWorkItemStatusRequest: A ReportWorkItemStatusRequest resource to be
      passed as the request body.
  """

  jobId = _messages.StringField(1, required=True)
  projectId = _messages.StringField(2, required=True)
  reportWorkItemStatusRequest = _messages.MessageField('ReportWorkItemStatusRequest', 3)


class DerivedSource(_messages.Message):
  """A DerivedSource object.

  Enums:
    DerivationModeValueValuesEnum:

  Fields:
    derivationMode: A DerivationModeValueValuesEnum attribute.
    source: A Source attribute.
  """

  class DerivationModeValueValuesEnum(_messages.Enum):
    """DerivationModeValueValuesEnum enum type.

    Values:
      SOURCE_DERIVATION_MODE_CHILD_OF_CURRENT: <no description>
      SOURCE_DERIVATION_MODE_INDEPENDENT: <no description>
      SOURCE_DERIVATION_MODE_SIBLING_OF_CURRENT: <no description>
      SOURCE_DERIVATION_MODE_UNKNOWN: <no description>
    """
    SOURCE_DERIVATION_MODE_CHILD_OF_CURRENT = 0
    SOURCE_DERIVATION_MODE_INDEPENDENT = 1
    SOURCE_DERIVATION_MODE_SIBLING_OF_CURRENT = 2
    SOURCE_DERIVATION_MODE_UNKNOWN = 3

  derivationMode = _messages.EnumField('DerivationModeValueValuesEnum', 1)
  source = _messages.MessageField('Source', 2)


class Disk(_messages.Message):
  """A Disk object.

  Fields:
    diskType: A string attribute.
    mountPoint: A string attribute.
    sizeGb: A integer attribute.
  """

  diskType = _messages.StringField(1)
  mountPoint = _messages.StringField(2)
  sizeGb = _messages.IntegerField(3, variant=_messages.Variant.INT32)


class DynamicSourceSplit(_messages.Message):
  """A DynamicSourceSplit object.

  Fields:
    primary: A DerivedSource attribute.
    residual: A DerivedSource attribute.
  """

  primary = _messages.MessageField('DerivedSource', 1)
  residual = _messages.MessageField('DerivedSource', 2)


class Environment(_messages.Message):
  """A Environment object.

  Messages:
    InternalExperimentsValue: A InternalExperimentsValue object.
    SdkPipelineOptionsValue: A SdkPipelineOptionsValue object.
    UserAgentValue: A UserAgentValue object.
    VersionValue: A VersionValue object.

  Fields:
    clusterManagerApiService: A string attribute.
    dataset: A string attribute.
    experiments: A string attribute.
    internalExperiments: A InternalExperimentsValue attribute.
    sdkPipelineOptions: A SdkPipelineOptionsValue attribute.
    tempStoragePrefix: A string attribute.
    userAgent: A UserAgentValue attribute.
    version: A VersionValue attribute.
    workerPools: A WorkerPool attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class InternalExperimentsValue(_messages.Message):
    """A InternalExperimentsValue object.

    Messages:
      AdditionalProperty: An additional property for a
        InternalExperimentsValue object.

    Fields:
      additionalProperties: Additional properties of type
        InternalExperimentsValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a InternalExperimentsValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class SdkPipelineOptionsValue(_messages.Message):
    """A SdkPipelineOptionsValue object.

    Messages:
      AdditionalProperty: An additional property for a SdkPipelineOptionsValue
        object.

    Fields:
      additionalProperties: Additional properties of type
        SdkPipelineOptionsValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a SdkPipelineOptionsValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class UserAgentValue(_messages.Message):
    """A UserAgentValue object.

    Messages:
      AdditionalProperty: An additional property for a UserAgentValue object.

    Fields:
      additionalProperties: Additional properties of type UserAgentValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a UserAgentValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class VersionValue(_messages.Message):
    """A VersionValue object.

    Messages:
      AdditionalProperty: An additional property for a VersionValue object.

    Fields:
      additionalProperties: Additional properties of type VersionValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a VersionValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  clusterManagerApiService = _messages.StringField(1)
  dataset = _messages.StringField(2)
  experiments = _messages.StringField(3, repeated=True)
  internalExperiments = _messages.MessageField('InternalExperimentsValue', 4)
  sdkPipelineOptions = _messages.MessageField('SdkPipelineOptionsValue', 5)
  tempStoragePrefix = _messages.StringField(6)
  userAgent = _messages.MessageField('UserAgentValue', 7)
  version = _messages.MessageField('VersionValue', 8)
  workerPools = _messages.MessageField('WorkerPool', 9, repeated=True)


class FlattenInstruction(_messages.Message):
  """A FlattenInstruction object.

  Fields:
    inputs: A InstructionInput attribute.
  """

  inputs = _messages.MessageField('InstructionInput', 1, repeated=True)


GoogleprotobufValue = extra_types.JsonValue


class InstructionInput(_messages.Message):
  """A InstructionInput object.

  Fields:
    outputNum: A integer attribute.
    producerInstructionIndex: A integer attribute.
  """

  outputNum = _messages.IntegerField(1, variant=_messages.Variant.INT32)
  producerInstructionIndex = _messages.IntegerField(2, variant=_messages.Variant.INT32)


class InstructionOutput(_messages.Message):
  """A InstructionOutput object.

  Messages:
    CodecValue: A CodecValue object.

  Fields:
    codec: A CodecValue attribute.
    name: A string attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class CodecValue(_messages.Message):
    """A CodecValue object.

    Messages:
      AdditionalProperty: An additional property for a CodecValue object.

    Fields:
      additionalProperties: Additional properties of type CodecValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a CodecValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  codec = _messages.MessageField('CodecValue', 1)
  name = _messages.StringField(2)


class Job(_messages.Message):
  """A Job object.

  Enums:
    CurrentStateValueValuesEnum:
    RequestedStateValueValuesEnum:
    TypeValueValuesEnum:

  Messages:
    TransformNameMappingValue: A TransformNameMappingValue object.

  Fields:
    clientRequestId: A string attribute.
    createTime: A string attribute.
    currentState: A CurrentStateValueValuesEnum attribute.
    currentStateTime: A string attribute.
    environment: A Environment attribute.
    executionInfo: A JobExecutionInfo attribute.
    id: A string attribute.
    name: A string attribute.
    projectId: A string attribute.
    replaceJobId: A string attribute.
    requestedState: A RequestedStateValueValuesEnum attribute.
    steps: A Step attribute.
    transformNameMapping: A TransformNameMappingValue attribute.
    type: A TypeValueValuesEnum attribute.
  """

  class CurrentStateValueValuesEnum(_messages.Enum):
    """CurrentStateValueValuesEnum enum type.

    Values:
      JOB_STATE_CANCELLED: <no description>
      JOB_STATE_DONE: <no description>
      JOB_STATE_FAILED: <no description>
      JOB_STATE_RUNNING: <no description>
      JOB_STATE_STOPPED: <no description>
      JOB_STATE_UNKNOWN: <no description>
    """
    JOB_STATE_CANCELLED = 0
    JOB_STATE_DONE = 1
    JOB_STATE_FAILED = 2
    JOB_STATE_RUNNING = 3
    JOB_STATE_STOPPED = 4
    JOB_STATE_UNKNOWN = 5

  class RequestedStateValueValuesEnum(_messages.Enum):
    """RequestedStateValueValuesEnum enum type.

    Values:
      JOB_STATE_CANCELLED: <no description>
      JOB_STATE_DONE: <no description>
      JOB_STATE_FAILED: <no description>
      JOB_STATE_RUNNING: <no description>
      JOB_STATE_STOPPED: <no description>
      JOB_STATE_UNKNOWN: <no description>
    """
    JOB_STATE_CANCELLED = 0
    JOB_STATE_DONE = 1
    JOB_STATE_FAILED = 2
    JOB_STATE_RUNNING = 3
    JOB_STATE_STOPPED = 4
    JOB_STATE_UNKNOWN = 5

  class TypeValueValuesEnum(_messages.Enum):
    """TypeValueValuesEnum enum type.

    Values:
      JOB_TYPE_BATCH: <no description>
      JOB_TYPE_STREAMING: <no description>
      JOB_TYPE_UNKNOWN: <no description>
    """
    JOB_TYPE_BATCH = 0
    JOB_TYPE_STREAMING = 1
    JOB_TYPE_UNKNOWN = 2

  @encoding.MapUnrecognizedFields('additionalProperties')
  class TransformNameMappingValue(_messages.Message):
    """A TransformNameMappingValue object.

    Messages:
      AdditionalProperty: An additional property for a
        TransformNameMappingValue object.

    Fields:
      additionalProperties: Additional properties of type
        TransformNameMappingValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a TransformNameMappingValue object.

      Fields:
        key: Name of the additional property.
        value: A string attribute.
      """

      key = _messages.StringField(1)
      value = _messages.StringField(2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  clientRequestId = _messages.StringField(1)
  createTime = _messages.StringField(2)
  currentState = _messages.EnumField('CurrentStateValueValuesEnum', 3)
  currentStateTime = _messages.StringField(4)
  environment = _messages.MessageField('Environment', 5)
  executionInfo = _messages.MessageField('JobExecutionInfo', 6)
  id = _messages.StringField(7)
  name = _messages.StringField(8)
  projectId = _messages.StringField(9)
  replaceJobId = _messages.StringField(10)
  requestedState = _messages.EnumField('RequestedStateValueValuesEnum', 11)
  steps = _messages.MessageField('Step', 12, repeated=True)
  transformNameMapping = _messages.MessageField('TransformNameMappingValue', 13)
  type = _messages.EnumField('TypeValueValuesEnum', 14)


class JobExecutionInfo(_messages.Message):
  """A JobExecutionInfo object.

  Messages:
    StagesValue: A StagesValue object.

  Fields:
    stages: A StagesValue attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class StagesValue(_messages.Message):
    """A StagesValue object.

    Messages:
      AdditionalProperty: An additional property for a StagesValue object.

    Fields:
      additionalProperties: Additional properties of type StagesValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a StagesValue object.

      Fields:
        key: Name of the additional property.
        value: A JobExecutionStageInfo attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('JobExecutionStageInfo', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  stages = _messages.MessageField('StagesValue', 1)


class JobExecutionStageInfo(_messages.Message):
  """A JobExecutionStageInfo object.

  Fields:
    stepName: A string attribute.
  """

  stepName = _messages.StringField(1, repeated=True)


class JobMessage(_messages.Message):
  """A JobMessage object.

  Enums:
    MessageImportanceValueValuesEnum:

  Fields:
    id: A string attribute.
    messageImportance: A MessageImportanceValueValuesEnum attribute.
    messageText: A string attribute.
    time: A string attribute.
  """

  class MessageImportanceValueValuesEnum(_messages.Enum):
    """MessageImportanceValueValuesEnum enum type.

    Values:
      JOB_MESSAGE_BASIC: <no description>
      JOB_MESSAGE_DEBUG: <no description>
      JOB_MESSAGE_DETAILED: <no description>
      JOB_MESSAGE_ERROR: <no description>
      JOB_MESSAGE_IMPORTANCE_UNKNOWN: <no description>
      JOB_MESSAGE_WARNING: <no description>
    """
    JOB_MESSAGE_BASIC = 0
    JOB_MESSAGE_DEBUG = 1
    JOB_MESSAGE_DETAILED = 2
    JOB_MESSAGE_ERROR = 3
    JOB_MESSAGE_IMPORTANCE_UNKNOWN = 4
    JOB_MESSAGE_WARNING = 5

  id = _messages.StringField(1)
  messageImportance = _messages.EnumField('MessageImportanceValueValuesEnum', 2)
  messageText = _messages.StringField(3)
  time = _messages.StringField(4)


class JobMetrics(_messages.Message):
  """A JobMetrics object.

  Fields:
    metricTime: A string attribute.
    metrics: A MetricUpdate attribute.
  """

  metricTime = _messages.StringField(1)
  metrics = _messages.MessageField('MetricUpdate', 2, repeated=True)


class KeyRangeDataDiskAssignment(_messages.Message):
  """A KeyRangeDataDiskAssignment object.

  Fields:
    dataDisk: A string attribute.
    end: A string attribute.
    start: A string attribute.
  """

  dataDisk = _messages.StringField(1)
  end = _messages.StringField(2)
  start = _messages.StringField(3)


class KeyRangeLocation(_messages.Message):
  """A KeyRangeLocation object.

  Fields:
    dataDisk: A string attribute.
    deliveryEndpoint: A string attribute.
    end: A string attribute.
    persistentDirectory: A string attribute.
    start: A string attribute.
  """

  dataDisk = _messages.StringField(1)
  deliveryEndpoint = _messages.StringField(2)
  end = _messages.StringField(3)
  persistentDirectory = _messages.StringField(4)
  start = _messages.StringField(5)


class LeaseWorkItemRequest(_messages.Message):
  """A LeaseWorkItemRequest object.

  Fields:
    currentWorkerTime: A string attribute.
    requestedLeaseDuration: A string attribute.
    workItemTypes: A string attribute.
    workerCapabilities: A string attribute.
    workerId: A string attribute.
  """

  currentWorkerTime = _messages.StringField(1)
  requestedLeaseDuration = _messages.StringField(2)
  workItemTypes = _messages.StringField(3, repeated=True)
  workerCapabilities = _messages.StringField(4, repeated=True)
  workerId = _messages.StringField(5)


class LeaseWorkItemResponse(_messages.Message):
  """A LeaseWorkItemResponse object.

  Fields:
    workItems: A WorkItem attribute.
  """

  workItems = _messages.MessageField('WorkItem', 1, repeated=True)


class ListJobMessagesResponse(_messages.Message):
  """A ListJobMessagesResponse object.

  Fields:
    jobMessages: A JobMessage attribute.
    nextPageToken: A string attribute.
  """

  jobMessages = _messages.MessageField('JobMessage', 1, repeated=True)
  nextPageToken = _messages.StringField(2)


class ListJobsResponse(_messages.Message):
  """A ListJobsResponse object.

  Fields:
    jobs: A Job attribute.
    nextPageToken: A string attribute.
  """

  jobs = _messages.MessageField('Job', 1, repeated=True)
  nextPageToken = _messages.StringField(2)


class MapTask(_messages.Message):
  """A MapTask object.

  Fields:
    instructions: A ParallelInstruction attribute.
    stageName: A string attribute.
    systemName: A string attribute.
  """

  instructions = _messages.MessageField('ParallelInstruction', 1, repeated=True)
  stageName = _messages.StringField(2)
  systemName = _messages.StringField(3)


class MetricStructuredName(_messages.Message):
  """A MetricStructuredName object.

  Messages:
    ContextValue: A ContextValue object.

  Fields:
    context: A ContextValue attribute.
    name: A string attribute.
    origin: A string attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class ContextValue(_messages.Message):
    """A ContextValue object.

    Messages:
      AdditionalProperty: An additional property for a ContextValue object.

    Fields:
      additionalProperties: Additional properties of type ContextValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a ContextValue object.

      Fields:
        key: Name of the additional property.
        value: A string attribute.
      """

      key = _messages.StringField(1)
      value = _messages.StringField(2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  context = _messages.MessageField('ContextValue', 1)
  name = _messages.StringField(2)
  origin = _messages.StringField(3)


class MetricUpdate(_messages.Message):
  """A MetricUpdate object.

  Fields:
    cumulative: A boolean attribute.
    internal: A GoogleprotobufValue attribute.
    kind: A string attribute.
    meanCount: A GoogleprotobufValue attribute.
    meanSum: A GoogleprotobufValue attribute.
    name: A MetricStructuredName attribute.
    scalar: A GoogleprotobufValue attribute.
    set: A GoogleprotobufValue attribute.
    updateTime: A string attribute.
  """

  cumulative = _messages.BooleanField(1)
  internal = _messages.MessageField('GoogleprotobufValue', 2)
  kind = _messages.StringField(3)
  meanCount = _messages.MessageField('GoogleprotobufValue', 4)
  meanSum = _messages.MessageField('GoogleprotobufValue', 5)
  name = _messages.MessageField('MetricStructuredName', 6)
  scalar = _messages.MessageField('GoogleprotobufValue', 7)
  set = _messages.MessageField('GoogleprotobufValue', 8)
  updateTime = _messages.StringField(9)


class MountedDataDisk(_messages.Message):
  """A MountedDataDisk object.

  Fields:
    dataDisk: A string attribute.
  """

  dataDisk = _messages.StringField(1)


class MultiOutputInfo(_messages.Message):
  """A MultiOutputInfo object.

  Fields:
    tag: A string attribute.
  """

  tag = _messages.StringField(1)


class Package(_messages.Message):
  """A Package object.

  Fields:
    location: A string attribute.
    name: A string attribute.
  """

  location = _messages.StringField(1)
  name = _messages.StringField(2)


class ParDoInstruction(_messages.Message):
  """A ParDoInstruction object.

  Messages:
    UserFnValue: A UserFnValue object.

  Fields:
    input: A InstructionInput attribute.
    multiOutputInfos: A MultiOutputInfo attribute.
    numOutputs: A integer attribute.
    sideInputs: A SideInputInfo attribute.
    userFn: A UserFnValue attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class UserFnValue(_messages.Message):
    """A UserFnValue object.

    Messages:
      AdditionalProperty: An additional property for a UserFnValue object.

    Fields:
      additionalProperties: Additional properties of type UserFnValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a UserFnValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  input = _messages.MessageField('InstructionInput', 1)
  multiOutputInfos = _messages.MessageField('MultiOutputInfo', 2, repeated=True)
  numOutputs = _messages.IntegerField(3, variant=_messages.Variant.INT32)
  sideInputs = _messages.MessageField('SideInputInfo', 4, repeated=True)
  userFn = _messages.MessageField('UserFnValue', 5)


class ParallelInstruction(_messages.Message):
  """A ParallelInstruction object.

  Fields:
    flatten: A FlattenInstruction attribute.
    name: A string attribute.
    outputs: A InstructionOutput attribute.
    parDo: A ParDoInstruction attribute.
    partialGroupByKey: A PartialGroupByKeyInstruction attribute.
    read: A ReadInstruction attribute.
    systemName: A string attribute.
    write: A WriteInstruction attribute.
  """

  flatten = _messages.MessageField('FlattenInstruction', 1)
  name = _messages.StringField(2)
  outputs = _messages.MessageField('InstructionOutput', 3, repeated=True)
  parDo = _messages.MessageField('ParDoInstruction', 4)
  partialGroupByKey = _messages.MessageField('PartialGroupByKeyInstruction', 5)
  read = _messages.MessageField('ReadInstruction', 6)
  systemName = _messages.StringField(7)
  write = _messages.MessageField('WriteInstruction', 8)


class PartialGroupByKeyInstruction(_messages.Message):
  """A PartialGroupByKeyInstruction object.

  Messages:
    InputElementCodecValue: A InputElementCodecValue object.
    ValueCombiningFnValue: A ValueCombiningFnValue object.

  Fields:
    input: A InstructionInput attribute.
    inputElementCodec: A InputElementCodecValue attribute.
    valueCombiningFn: A ValueCombiningFnValue attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class InputElementCodecValue(_messages.Message):
    """A InputElementCodecValue object.

    Messages:
      AdditionalProperty: An additional property for a InputElementCodecValue
        object.

    Fields:
      additionalProperties: Additional properties of type
        InputElementCodecValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a InputElementCodecValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class ValueCombiningFnValue(_messages.Message):
    """A ValueCombiningFnValue object.

    Messages:
      AdditionalProperty: An additional property for a ValueCombiningFnValue
        object.

    Fields:
      additionalProperties: Additional properties of type
        ValueCombiningFnValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a ValueCombiningFnValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  input = _messages.MessageField('InstructionInput', 1)
  inputElementCodec = _messages.MessageField('InputElementCodecValue', 2)
  valueCombiningFn = _messages.MessageField('ValueCombiningFnValue', 3)


class Position(_messages.Message):
  """A Position object.

  Fields:
    byteOffset: A string attribute.
    end: A boolean attribute.
    key: A string attribute.
    recordIndex: A string attribute.
    shufflePosition: A string attribute.
  """

  byteOffset = _messages.IntegerField(1)
  end = _messages.BooleanField(2)
  key = _messages.StringField(3)
  recordIndex = _messages.IntegerField(4)
  shufflePosition = _messages.StringField(5)


class PubsubLocation(_messages.Message):
  """A PubsubLocation object.

  Fields:
    dropLateData: A boolean attribute.
    idLabel: A string attribute.
    subscription: A string attribute.
    timestampLabel: A string attribute.
    topic: A string attribute.
    trackingSubscription: A string attribute.
  """

  dropLateData = _messages.BooleanField(1)
  idLabel = _messages.StringField(2)
  subscription = _messages.StringField(3)
  timestampLabel = _messages.StringField(4)
  topic = _messages.StringField(5)
  trackingSubscription = _messages.StringField(6)


class ReadInstruction(_messages.Message):
  """A ReadInstruction object.

  Fields:
    source: A Source attribute.
  """

  source = _messages.MessageField('Source', 1)


class ReportWorkItemStatusRequest(_messages.Message):
  """A ReportWorkItemStatusRequest object.

  Fields:
    currentWorkerTime: A string attribute.
    workItemStatuses: A WorkItemStatus attribute.
    workerId: A string attribute.
  """

  currentWorkerTime = _messages.StringField(1)
  workItemStatuses = _messages.MessageField('WorkItemStatus', 2, repeated=True)
  workerId = _messages.StringField(3)


class ReportWorkItemStatusResponse(_messages.Message):
  """A ReportWorkItemStatusResponse object.

  Fields:
    workItemServiceStates: A WorkItemServiceState attribute.
  """

  workItemServiceStates = _messages.MessageField('WorkItemServiceState', 1, repeated=True)


class SeqMapTask(_messages.Message):
  """A SeqMapTask object.

  Messages:
    UserFnValue: A UserFnValue object.

  Fields:
    inputs: A SideInputInfo attribute.
    name: A string attribute.
    outputInfos: A SeqMapTaskOutputInfo attribute.
    stageName: A string attribute.
    systemName: A string attribute.
    userFn: A UserFnValue attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class UserFnValue(_messages.Message):
    """A UserFnValue object.

    Messages:
      AdditionalProperty: An additional property for a UserFnValue object.

    Fields:
      additionalProperties: Additional properties of type UserFnValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a UserFnValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  inputs = _messages.MessageField('SideInputInfo', 1, repeated=True)
  name = _messages.StringField(2)
  outputInfos = _messages.MessageField('SeqMapTaskOutputInfo', 3, repeated=True)
  stageName = _messages.StringField(4)
  systemName = _messages.StringField(5)
  userFn = _messages.MessageField('UserFnValue', 6)


class SeqMapTaskOutputInfo(_messages.Message):
  """A SeqMapTaskOutputInfo object.

  Fields:
    sink: A Sink attribute.
    tag: A string attribute.
  """

  sink = _messages.MessageField('Sink', 1)
  tag = _messages.StringField(2)


class ShellTask(_messages.Message):
  """A ShellTask object.

  Fields:
    command: A string attribute.
    exitCode: A integer attribute.
  """

  command = _messages.StringField(1)
  exitCode = _messages.IntegerField(2, variant=_messages.Variant.INT32)


class SideInputInfo(_messages.Message):
  """A SideInputInfo object.

  Messages:
    KindValue: A KindValue object.

  Fields:
    kind: A KindValue attribute.
    sources: A Source attribute.
    tag: A string attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class KindValue(_messages.Message):
    """A KindValue object.

    Messages:
      AdditionalProperty: An additional property for a KindValue object.

    Fields:
      additionalProperties: Additional properties of type KindValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a KindValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  kind = _messages.MessageField('KindValue', 1)
  sources = _messages.MessageField('Source', 2, repeated=True)
  tag = _messages.StringField(3)


class Sink(_messages.Message):
  """A Sink object.

  Messages:
    CodecValue: A CodecValue object.
    SpecValue: A SpecValue object.

  Fields:
    codec: A CodecValue attribute.
    spec: A SpecValue attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class CodecValue(_messages.Message):
    """A CodecValue object.

    Messages:
      AdditionalProperty: An additional property for a CodecValue object.

    Fields:
      additionalProperties: Additional properties of type CodecValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a CodecValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class SpecValue(_messages.Message):
    """A SpecValue object.

    Messages:
      AdditionalProperty: An additional property for a SpecValue object.

    Fields:
      additionalProperties: Additional properties of type SpecValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a SpecValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  codec = _messages.MessageField('CodecValue', 1)
  spec = _messages.MessageField('SpecValue', 2)


class Source(_messages.Message):
  """A Source object.

  Messages:
    BaseSpecsValueListEntry: A BaseSpecsValueListEntry object.
    CodecValue: A CodecValue object.
    SpecValue: A SpecValue object.

  Fields:
    baseSpecs: A BaseSpecsValueListEntry attribute.
    codec: A CodecValue attribute.
    doesNotNeedSplitting: A boolean attribute.
    metadata: A SourceMetadata attribute.
    spec: A SpecValue attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class BaseSpecsValueListEntry(_messages.Message):
    """A BaseSpecsValueListEntry object.

    Messages:
      AdditionalProperty: An additional property for a BaseSpecsValueListEntry
        object.

    Fields:
      additionalProperties: Additional properties of type
        BaseSpecsValueListEntry
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a BaseSpecsValueListEntry object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class CodecValue(_messages.Message):
    """A CodecValue object.

    Messages:
      AdditionalProperty: An additional property for a CodecValue object.

    Fields:
      additionalProperties: Additional properties of type CodecValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a CodecValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class SpecValue(_messages.Message):
    """A SpecValue object.

    Messages:
      AdditionalProperty: An additional property for a SpecValue object.

    Fields:
      additionalProperties: Additional properties of type SpecValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a SpecValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  baseSpecs = _messages.MessageField('BaseSpecsValueListEntry', 1, repeated=True)
  codec = _messages.MessageField('CodecValue', 2)
  doesNotNeedSplitting = _messages.BooleanField(3)
  metadata = _messages.MessageField('SourceMetadata', 4)
  spec = _messages.MessageField('SpecValue', 5)


class SourceFork(_messages.Message):
  """A SourceFork object.

  Fields:
    primary: A SourceSplitShard attribute.
    primarySource: A DerivedSource attribute.
    residual: A SourceSplitShard attribute.
    residualSource: A DerivedSource attribute.
  """

  primary = _messages.MessageField('SourceSplitShard', 1)
  primarySource = _messages.MessageField('DerivedSource', 2)
  residual = _messages.MessageField('SourceSplitShard', 3)
  residualSource = _messages.MessageField('DerivedSource', 4)


class SourceGetMetadataRequest(_messages.Message):
  """A SourceGetMetadataRequest object.

  Fields:
    source: A Source attribute.
  """

  source = _messages.MessageField('Source', 1)


class SourceGetMetadataResponse(_messages.Message):
  """A SourceGetMetadataResponse object.

  Fields:
    metadata: A SourceMetadata attribute.
  """

  metadata = _messages.MessageField('SourceMetadata', 1)


class SourceMetadata(_messages.Message):
  """A SourceMetadata object.

  Fields:
    estimatedSizeBytes: A string attribute.
    infinite: A boolean attribute.
    producesSortedKeys: A boolean attribute.
  """

  estimatedSizeBytes = _messages.IntegerField(1)
  infinite = _messages.BooleanField(2)
  producesSortedKeys = _messages.BooleanField(3)


class SourceOperationRequest(_messages.Message):
  """A SourceOperationRequest object.

  Fields:
    getMetadata: A SourceGetMetadataRequest attribute.
    split: A SourceSplitRequest attribute.
  """

  getMetadata = _messages.MessageField('SourceGetMetadataRequest', 1)
  split = _messages.MessageField('SourceSplitRequest', 2)


class SourceOperationResponse(_messages.Message):
  """A SourceOperationResponse object.

  Fields:
    getMetadata: A SourceGetMetadataResponse attribute.
    split: A SourceSplitResponse attribute.
  """

  getMetadata = _messages.MessageField('SourceGetMetadataResponse', 1)
  split = _messages.MessageField('SourceSplitResponse', 2)


class SourceSplitOptions(_messages.Message):
  """A SourceSplitOptions object.

  Fields:
    desiredBundleSizeBytes: A string attribute.
    desiredShardSizeBytes: A string attribute.
  """

  desiredBundleSizeBytes = _messages.IntegerField(1)
  desiredShardSizeBytes = _messages.IntegerField(2)


class SourceSplitRequest(_messages.Message):
  """A SourceSplitRequest object.

  Fields:
    options: A SourceSplitOptions attribute.
    source: A Source attribute.
  """

  options = _messages.MessageField('SourceSplitOptions', 1)
  source = _messages.MessageField('Source', 2)


class SourceSplitResponse(_messages.Message):
  """A SourceSplitResponse object.

  Enums:
    OutcomeValueValuesEnum:

  Fields:
    bundles: A DerivedSource attribute.
    outcome: A OutcomeValueValuesEnum attribute.
    shards: A SourceSplitShard attribute.
  """

  class OutcomeValueValuesEnum(_messages.Enum):
    """OutcomeValueValuesEnum enum type.

    Values:
      SOURCE_SPLIT_OUTCOME_SPLITTING_HAPPENED: <no description>
      SOURCE_SPLIT_OUTCOME_UNKNOWN: <no description>
      SOURCE_SPLIT_OUTCOME_USE_CURRENT: <no description>
    """
    SOURCE_SPLIT_OUTCOME_SPLITTING_HAPPENED = 0
    SOURCE_SPLIT_OUTCOME_UNKNOWN = 1
    SOURCE_SPLIT_OUTCOME_USE_CURRENT = 2

  bundles = _messages.MessageField('DerivedSource', 1, repeated=True)
  outcome = _messages.EnumField('OutcomeValueValuesEnum', 2)
  shards = _messages.MessageField('SourceSplitShard', 3, repeated=True)


class SourceSplitShard(_messages.Message):
  """A SourceSplitShard object.

  Enums:
    DerivationModeValueValuesEnum:

  Fields:
    derivationMode: A DerivationModeValueValuesEnum attribute.
    source: A Source attribute.
  """

  class DerivationModeValueValuesEnum(_messages.Enum):
    """DerivationModeValueValuesEnum enum type.

    Values:
      SOURCE_DERIVATION_MODE_CHILD_OF_CURRENT: <no description>
      SOURCE_DERIVATION_MODE_INDEPENDENT: <no description>
      SOURCE_DERIVATION_MODE_SIBLING_OF_CURRENT: <no description>
      SOURCE_DERIVATION_MODE_UNKNOWN: <no description>
    """
    SOURCE_DERIVATION_MODE_CHILD_OF_CURRENT = 0
    SOURCE_DERIVATION_MODE_INDEPENDENT = 1
    SOURCE_DERIVATION_MODE_SIBLING_OF_CURRENT = 2
    SOURCE_DERIVATION_MODE_UNKNOWN = 3

  derivationMode = _messages.EnumField('DerivationModeValueValuesEnum', 1)
  source = _messages.MessageField('Source', 2)


class StandardQueryParameters(_messages.Message):
  """Query parameters accepted by all methods.

  Enums:
    AltValueValuesEnum: Data format for the response.

  Fields:
    alt: Data format for the response.
    fields: Selector specifying which fields to include in a partial response.
    key: API key. Your API key identifies your project and provides you with
      API access, quota, and reports. Required unless you provide an OAuth 2.0
      token.
    oauth_token: OAuth 2.0 token for the current user.
    prettyPrint: Returns response with indentations and line breaks.
    quotaUser: Available to use for quota purposes for server-side
      applications. Can be any arbitrary string assigned to a user, but should
      not exceed 40 characters. Overrides userIp if both are provided.
    trace: A tracing token of the form "token:<tokenid>" or "email:<ldap>" to
      include in api requests.
    userIp: IP address of the site where the request originates. Use this if
      you want to enforce per-user limits.
  """

  class AltValueValuesEnum(_messages.Enum):
    """Data format for the response.

    Values:
      json: Responses with Content-Type of application/json
    """
    json = 0

  alt = _messages.EnumField('AltValueValuesEnum', 1, default=u'json')
  fields = _messages.StringField(2)
  key = _messages.StringField(3)
  oauth_token = _messages.StringField(4)
  prettyPrint = _messages.BooleanField(5, default=True)
  quotaUser = _messages.StringField(6)
  trace = _messages.StringField(7)
  userIp = _messages.StringField(8)


class Status(_messages.Message):
  """A Status object.

  Messages:
    DetailsValueListEntry: A DetailsValueListEntry object.

  Fields:
    code: A integer attribute.
    details: A DetailsValueListEntry attribute.
    message: A string attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class DetailsValueListEntry(_messages.Message):
    """A DetailsValueListEntry object.

    Messages:
      AdditionalProperty: An additional property for a DetailsValueListEntry
        object.

    Fields:
      additionalProperties: Additional properties of type
        DetailsValueListEntry
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a DetailsValueListEntry object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  code = _messages.IntegerField(1, variant=_messages.Variant.INT32)
  details = _messages.MessageField('DetailsValueListEntry', 2, repeated=True)
  message = _messages.StringField(3)


class Step(_messages.Message):
  """A Step object.

  Messages:
    PropertiesValue: A PropertiesValue object.

  Fields:
    kind: A string attribute.
    name: A string attribute.
    properties: A PropertiesValue attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class PropertiesValue(_messages.Message):
    """A PropertiesValue object.

    Messages:
      AdditionalProperty: An additional property for a PropertiesValue object.

    Fields:
      additionalProperties: Additional properties of type PropertiesValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a PropertiesValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  kind = _messages.StringField(1)
  name = _messages.StringField(2)
  properties = _messages.MessageField('PropertiesValue', 3)


class StreamLocation(_messages.Message):
  """A StreamLocation object.

  Fields:
    customSourceLocation: A CustomSourceLocation attribute.
    pubsubLocation: A PubsubLocation attribute.
    sideInputLocation: A StreamingSideInputLocation attribute.
    streamingStageLocation: A StreamingStageLocation attribute.
  """

  customSourceLocation = _messages.MessageField('CustomSourceLocation', 1)
  pubsubLocation = _messages.MessageField('PubsubLocation', 2)
  sideInputLocation = _messages.MessageField('StreamingSideInputLocation', 3)
  streamingStageLocation = _messages.MessageField('StreamingStageLocation', 4)


class StreamingComputationRanges(_messages.Message):
  """A StreamingComputationRanges object.

  Fields:
    computationId: A string attribute.
    rangeAssignments: A KeyRangeDataDiskAssignment attribute.
  """

  computationId = _messages.StringField(1)
  rangeAssignments = _messages.MessageField('KeyRangeDataDiskAssignment', 2, repeated=True)


class StreamingComputationTask(_messages.Message):
  """A StreamingComputationTask object.

  Enums:
    TaskTypeValueValuesEnum:

  Fields:
    computationRanges: A StreamingComputationRanges attribute.
    dataDisks: A MountedDataDisk attribute.
    taskType: A TaskTypeValueValuesEnum attribute.
  """

  class TaskTypeValueValuesEnum(_messages.Enum):
    """TaskTypeValueValuesEnum enum type.

    Values:
      STREAMING_COMPUTATION_TASK_START: <no description>
      STREAMING_COMPUTATION_TASK_STOP: <no description>
      STREAMING_COMPUTATION_TASK_UNKNOWN: <no description>
    """
    STREAMING_COMPUTATION_TASK_START = 0
    STREAMING_COMPUTATION_TASK_STOP = 1
    STREAMING_COMPUTATION_TASK_UNKNOWN = 2

  computationRanges = _messages.MessageField('StreamingComputationRanges', 1, repeated=True)
  dataDisks = _messages.MessageField('MountedDataDisk', 2, repeated=True)
  taskType = _messages.EnumField('TaskTypeValueValuesEnum', 3)


class StreamingSetupTask(_messages.Message):
  """A StreamingSetupTask object.

  Fields:
    receiveWorkPort: A integer attribute.
    streamingComputationTopology: A TopologyConfig attribute.
    workerHarnessPort: A integer attribute.
  """

  receiveWorkPort = _messages.IntegerField(1, variant=_messages.Variant.INT32)
  streamingComputationTopology = _messages.MessageField('TopologyConfig', 2)
  workerHarnessPort = _messages.IntegerField(3, variant=_messages.Variant.INT32)


class StreamingSideInputLocation(_messages.Message):
  """A StreamingSideInputLocation object.

  Fields:
    tag: A string attribute.
  """

  tag = _messages.StringField(1)


class StreamingStageLocation(_messages.Message):
  """A StreamingStageLocation object.

  Fields:
    streamId: A string attribute.
  """

  streamId = _messages.StringField(1)


class TaskRunnerSettings(_messages.Message):
  """A TaskRunnerSettings object.

  Fields:
    alsologtostderr: A boolean attribute.
    baseTaskDir: A string attribute.
    baseUrl: A string attribute.
    commandlinesFileName: A string attribute.
    continueOnException: A boolean attribute.
    dataflowApiVersion: A string attribute.
    harnessCommand: A string attribute.
    languageHint: A string attribute.
    logDir: A string attribute.
    logToSerialconsole: A boolean attribute.
    logUploadLocation: A string attribute.
    oauthScopes: A string attribute.
    parallelWorkerSettings: A WorkerSettings attribute.
    streamingWorkerMainClass: A string attribute.
    taskGroup: A string attribute.
    taskUser: A string attribute.
    tempStoragePrefix: A string attribute.
    vmId: A string attribute.
    workflowFileName: A string attribute.
  """

  alsologtostderr = _messages.BooleanField(1)
  baseTaskDir = _messages.StringField(2)
  baseUrl = _messages.StringField(3)
  commandlinesFileName = _messages.StringField(4)
  continueOnException = _messages.BooleanField(5)
  dataflowApiVersion = _messages.StringField(6)
  harnessCommand = _messages.StringField(7)
  languageHint = _messages.StringField(8)
  logDir = _messages.StringField(9)
  logToSerialconsole = _messages.BooleanField(10)
  logUploadLocation = _messages.StringField(11)
  oauthScopes = _messages.StringField(12, repeated=True)
  parallelWorkerSettings = _messages.MessageField('WorkerSettings', 13)
  streamingWorkerMainClass = _messages.StringField(14)
  taskGroup = _messages.StringField(15)
  taskUser = _messages.StringField(16)
  tempStoragePrefix = _messages.StringField(17)
  vmId = _messages.StringField(18)
  workflowFileName = _messages.StringField(19)


class TopologyConfig(_messages.Message):
  """A TopologyConfig object.

  Fields:
    computations: A ComputationTopology attribute.
    dataDiskAssignments: A DataDiskAssignment attribute.
  """

  computations = _messages.MessageField('ComputationTopology', 1, repeated=True)
  dataDiskAssignments = _messages.MessageField('DataDiskAssignment', 2, repeated=True)


class WorkItem(_messages.Message):
  """A WorkItem object.

  Fields:
    configuration: A string attribute.
    id: A string attribute.
    initialReportIndex: A string attribute.
    jobId: A string attribute.
    leaseExpireTime: A string attribute.
    mapTask: A MapTask attribute.
    packages: A Package attribute.
    projectId: A string attribute.
    reportStatusInterval: A string attribute.
    seqMapTask: A SeqMapTask attribute.
    shellTask: A ShellTask attribute.
    sourceOperationTask: A SourceOperationRequest attribute.
    streamingComputationTask: A StreamingComputationTask attribute.
    streamingSetupTask: A StreamingSetupTask attribute.
  """

  configuration = _messages.StringField(1)
  id = _messages.IntegerField(2)
  initialReportIndex = _messages.IntegerField(3)
  jobId = _messages.StringField(4)
  leaseExpireTime = _messages.StringField(5)
  mapTask = _messages.MessageField('MapTask', 6)
  packages = _messages.MessageField('Package', 7, repeated=True)
  projectId = _messages.StringField(8)
  reportStatusInterval = _messages.StringField(9)
  seqMapTask = _messages.MessageField('SeqMapTask', 10)
  shellTask = _messages.MessageField('ShellTask', 11)
  sourceOperationTask = _messages.MessageField('SourceOperationRequest', 12)
  streamingComputationTask = _messages.MessageField('StreamingComputationTask', 13)
  streamingSetupTask = _messages.MessageField('StreamingSetupTask', 14)


class WorkItemServiceState(_messages.Message):
  """A WorkItemServiceState object.

  Messages:
    HarnessDataValue: A HarnessDataValue object.

  Fields:
    harnessData: A HarnessDataValue attribute.
    leaseExpireTime: A string attribute.
    nextReportIndex: A string attribute.
    reportStatusInterval: A string attribute.
    suggestedStopPoint: A ApproximateProgress attribute.
    suggestedStopPosition: A Position attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class HarnessDataValue(_messages.Message):
    """A HarnessDataValue object.

    Messages:
      AdditionalProperty: An additional property for a HarnessDataValue
        object.

    Fields:
      additionalProperties: Additional properties of type HarnessDataValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a HarnessDataValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  harnessData = _messages.MessageField('HarnessDataValue', 1)
  leaseExpireTime = _messages.StringField(2)
  nextReportIndex = _messages.IntegerField(3)
  reportStatusInterval = _messages.StringField(4)
  suggestedStopPoint = _messages.MessageField('ApproximateProgress', 5)
  suggestedStopPosition = _messages.MessageField('Position', 6)


class WorkItemStatus(_messages.Message):
  """A WorkItemStatus object.

  Fields:
    completed: A boolean attribute.
    dynamicSourceSplit: A DynamicSourceSplit attribute.
    errors: A Status attribute.
    metricUpdates: A MetricUpdate attribute.
    progress: A ApproximateProgress attribute.
    reportIndex: A string attribute.
    requestedLeaseDuration: A string attribute.
    sourceFork: A SourceFork attribute.
    sourceOperationResponse: A SourceOperationResponse attribute.
    stopPosition: A Position attribute.
    workItemId: A string attribute.
  """

  completed = _messages.BooleanField(1)
  dynamicSourceSplit = _messages.MessageField('DynamicSourceSplit', 2)
  errors = _messages.MessageField('Status', 3, repeated=True)
  metricUpdates = _messages.MessageField('MetricUpdate', 4, repeated=True)
  progress = _messages.MessageField('ApproximateProgress', 5)
  reportIndex = _messages.IntegerField(6)
  requestedLeaseDuration = _messages.StringField(7)
  sourceFork = _messages.MessageField('SourceFork', 8)
  sourceOperationResponse = _messages.MessageField('SourceOperationResponse', 9)
  stopPosition = _messages.MessageField('Position', 10)
  workItemId = _messages.StringField(11)


class WorkerPool(_messages.Message):
  """A WorkerPool object.

  Enums:
    DefaultPackageSetValueValuesEnum:
    TeardownPolicyValueValuesEnum:

  Messages:
    MetadataValue: A MetadataValue object.
    PoolArgsValue: A PoolArgsValue object.

  Fields:
    autoscalingSettings: A AutoscalingSettings attribute.
    dataDisks: A Disk attribute.
    defaultPackageSet: A DefaultPackageSetValueValuesEnum attribute.
    diskSizeGb: A integer attribute.
    diskSourceImage: A string attribute.
    diskType: A string attribute.
    kind: A string attribute.
    machineType: A string attribute.
    metadata: A MetadataValue attribute.
    network: A string attribute.
    numWorkers: A integer attribute.
    onHostMaintenance: A string attribute.
    packages: A Package attribute.
    poolArgs: A PoolArgsValue attribute.
    taskrunnerSettings: A TaskRunnerSettings attribute.
    teardownPolicy: A TeardownPolicyValueValuesEnum attribute.
    zone: A string attribute.
  """

  class DefaultPackageSetValueValuesEnum(_messages.Enum):
    """DefaultPackageSetValueValuesEnum enum type.

    Values:
      DEFAULT_PACKAGE_SET_JAVA: <no description>
      DEFAULT_PACKAGE_SET_NONE: <no description>
      DEFAULT_PACKAGE_SET_PYTHON: <no description>
      DEFAULT_PACKAGE_SET_UNKNOWN: <no description>
    """
    DEFAULT_PACKAGE_SET_JAVA = 0
    DEFAULT_PACKAGE_SET_NONE = 1
    DEFAULT_PACKAGE_SET_PYTHON = 2
    DEFAULT_PACKAGE_SET_UNKNOWN = 3

  class TeardownPolicyValueValuesEnum(_messages.Enum):
    """TeardownPolicyValueValuesEnum enum type.

    Values:
      TEARDOWN_ALWAYS: <no description>
      TEARDOWN_NEVER: <no description>
      TEARDOWN_ON_SUCCESS: <no description>
      TEARDOWN_POLICY_UNKNOWN: <no description>
    """
    TEARDOWN_ALWAYS = 0
    TEARDOWN_NEVER = 1
    TEARDOWN_ON_SUCCESS = 2
    TEARDOWN_POLICY_UNKNOWN = 3

  @encoding.MapUnrecognizedFields('additionalProperties')
  class MetadataValue(_messages.Message):
    """A MetadataValue object.

    Messages:
      AdditionalProperty: An additional property for a MetadataValue object.

    Fields:
      additionalProperties: Additional properties of type MetadataValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a MetadataValue object.

      Fields:
        key: Name of the additional property.
        value: A string attribute.
      """

      key = _messages.StringField(1)
      value = _messages.StringField(2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class PoolArgsValue(_messages.Message):
    """A PoolArgsValue object.

    Messages:
      AdditionalProperty: An additional property for a PoolArgsValue object.

    Fields:
      additionalProperties: Additional properties of type PoolArgsValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a PoolArgsValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  autoscalingSettings = _messages.MessageField('AutoscalingSettings', 1)
  dataDisks = _messages.MessageField('Disk', 2, repeated=True)
  defaultPackageSet = _messages.EnumField('DefaultPackageSetValueValuesEnum', 3)
  diskSizeGb = _messages.IntegerField(4, variant=_messages.Variant.INT32)
  diskSourceImage = _messages.StringField(5)
  diskType = _messages.StringField(6)
  kind = _messages.StringField(7)
  machineType = _messages.StringField(8)
  metadata = _messages.MessageField('MetadataValue', 9)
  network = _messages.StringField(10)
  numWorkers = _messages.IntegerField(11, variant=_messages.Variant.INT32)
  onHostMaintenance = _messages.StringField(12)
  packages = _messages.MessageField('Package', 13, repeated=True)
  poolArgs = _messages.MessageField('PoolArgsValue', 14)
  taskrunnerSettings = _messages.MessageField('TaskRunnerSettings', 15)
  teardownPolicy = _messages.EnumField('TeardownPolicyValueValuesEnum', 16)
  zone = _messages.StringField(17)


class WorkerSettings(_messages.Message):
  """A WorkerSettings object.

  Fields:
    baseUrl: A string attribute.
    reportingEnabled: A boolean attribute.
    servicePath: A string attribute.
    shuffleServicePath: A string attribute.
    tempStoragePrefix: A string attribute.
    workerId: A string attribute.
  """

  baseUrl = _messages.StringField(1)
  reportingEnabled = _messages.BooleanField(2)
  servicePath = _messages.StringField(3)
  shuffleServicePath = _messages.StringField(4)
  tempStoragePrefix = _messages.StringField(5)
  workerId = _messages.StringField(6)


class WriteInstruction(_messages.Message):
  """A WriteInstruction object.

  Fields:
    input: A InstructionInput attribute.
    sink: A Sink attribute.
  """

  input = _messages.MessageField('InstructionInput', 1)
  sink = _messages.MessageField('Sink', 2)


