"""Generated message classes for apheleia version v1beta1.

A Google Apheleia service.
"""
# NOTE: This file is autogenerated and should not be edited by hand.

from protorpc import messages as _messages

from googlecloudapis.apitools.base.py import encoding


package = 'apheleia'


class ApheleiaProjectsRegionsFunctionsCreateRequest(_messages.Message):
  """A ApheleiaProjectsRegionsFunctionsCreateRequest object.

  Fields:
    function: A Function resource to be passed as the request body.
    location: The project and region in which the function should be created,
      specified in the format: projects/*/regions/*
  """

  function = _messages.MessageField('Function', 1)
  location = _messages.StringField(2, required=True)


class ApheleiaProjectsRegionsFunctionsDeleteRequest(_messages.Message):
  """A ApheleiaProjectsRegionsFunctionsDeleteRequest object.

  Fields:
    name: The name of the function which should be deleted.
  """

  name = _messages.StringField(1, required=True)


class ApheleiaProjectsRegionsFunctionsGetRequest(_messages.Message):
  """A ApheleiaProjectsRegionsFunctionsGetRequest object.

  Fields:
    name: The name of the function which details should be obtained.
  """

  name = _messages.StringField(1, required=True)


class ApheleiaProjectsRegionsFunctionsListRequest(_messages.Message):
  """A ApheleiaProjectsRegionsFunctionsListRequest object.

  Fields:
    location: The project and region in which the function should be created,
      specified in the format: projects/*/regions/*
    pageSize: Maximum number of functions to return.
    pageToken: The value returned by the last ListFunctionsResponse; indicates
      that this is a continuation of a prior ListFunctions call, and that the
      system should return the next page of data.
  """

  location = _messages.StringField(1, required=True)
  pageSize = _messages.IntegerField(2, variant=_messages.Variant.UINT32)
  pageToken = _messages.StringField(3)


class Function(_messages.Message):
  """Describes a function containing user computation.

  Enums:
    StatusValueValuesEnum: [Output only] Status of the function deployment.

  Fields:
    gcsUrl: GCS url containing the function.
    name: A user-defined name of the function. Function names must be unique
      globally and match regexp: projects/*/regions/*/functions/*
    status: [Output only] Status of the function deployment.
    triggers: List of triggers.
  """

  class StatusValueValuesEnum(_messages.Enum):
    """[Output only] Status of the function deployment.

    Values:
      READY: Successfully deployed.
      FAILED: Not deployed correctly - behavior is undefined. The item should
        be updated or deleted to move it out of this state.
      DEPLOYING: Creation or update in progress.
      DELETING: Deletion in progress.
    """
    READY = 0
    FAILED = 1
    DEPLOYING = 2
    DELETING = 3

  gcsUrl = _messages.StringField(1)
  name = _messages.StringField(2)
  status = _messages.EnumField('StatusValueValuesEnum', 3)
  triggers = _messages.MessageField('Trigger', 4, repeated=True)


class ListFunctionsResponse(_messages.Message):
  """Response for the ListFunctions method.

  Fields:
    functions: The functions that match the request.
    nextPageToken: If not empty, indicates that there may be more functions
      that match the request; this value should be passed in a new
      ListFunctionsRequest to get more functions.
  """

  functions = _messages.MessageField('Function', 1, repeated=True)
  nextPageToken = _messages.StringField(2)


class Operation(_messages.Message):
  """This resource represents a long-running operation that is the result of a
  network API call.

  Messages:
    MetadataValue: Some service-specific metadata associated with the
      operation.  It typically contains progress information and common
      metadata such as create time. Some services may not provide such
      metadata.  Any method that returns a long-running operation should
      document the metadata type, if any.
    ResponseValue: The normal response of the operation in case of success.
      If the original method returns no data on success, such as `Delete`, the
      response will be `google.protobuf.Empty`.  If the original method is
      standard `Get`/`Create`/`Update`, the response should be the resource.
      For other methods, the response should have the type `XxxResponse`,
      where `Xxx` is the original method name.  For example, if the original
      method name is `TakeSnapshot()`, the inferred response type will be
      `TakeSnapshotResponse`.

  Fields:
    done: If the value is false, it means the operation is still in progress.
      If true, the operation is completed and the `result` is available.
    error: The error result of the operation in case of failure.
    metadata: Some service-specific metadata associated with the operation.
      It typically contains progress information and common metadata such as
      create time. Some services may not provide such metadata.  Any method
      that returns a long-running operation should document the metadata type,
      if any.
    name: The server-assigned name, which is only unique within the same
      service that originally returns it. If you use the default HTTP mapping
      above, the `name` should have the format of
      "operations/some/unique/name".
    response: The normal response of the operation in case of success.  If the
      original method returns no data on success, such as `Delete`, the
      response will be `google.protobuf.Empty`.  If the original method is
      standard `Get`/`Create`/`Update`, the response should be the resource.
      For other methods, the response should have the type `XxxResponse`,
      where `Xxx` is the original method name.  For example, if the original
      method name is `TakeSnapshot()`, the inferred response type will be
      `TakeSnapshotResponse`.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class MetadataValue(_messages.Message):
    """Some service-specific metadata associated with the operation.  It
    typically contains progress information and common metadata such as create
    time. Some services may not provide such metadata.  Any method that
    returns a long-running operation should document the metadata type, if
    any.

    Messages:
      AdditionalProperty: An additional property for a MetadataValue object.

    Fields:
      additionalProperties: Properties of the object. Contains field @ype with
        type URL.
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a MetadataValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class ResponseValue(_messages.Message):
    """The normal response of the operation in case of success.  If the
    original method returns no data on success, such as `Delete`, the response
    will be `google.protobuf.Empty`.  If the original method is standard
    `Get`/`Create`/`Update`, the response should be the resource.  For other
    methods, the response should have the type `XxxResponse`, where `Xxx` is
    the original method name.  For example, if the original method name is
    `TakeSnapshot()`, the inferred response type will be
    `TakeSnapshotResponse`.

    Messages:
      AdditionalProperty: An additional property for a ResponseValue object.

    Fields:
      additionalProperties: Properties of the object. Contains field @ype with
        type URL.
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a ResponseValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  done = _messages.BooleanField(1)
  error = _messages.MessageField('Status', 2)
  metadata = _messages.MessageField('MetadataValue', 3)
  name = _messages.StringField(4)
  response = _messages.MessageField('ResponseValue', 5)


class PubsubEventSource(_messages.Message):
  """Describes a Pub/Sub event source.

  Fields:
    topic: A name of Pub/Sub topic which is the source of events.
  """

  topic = _messages.StringField(1)


class StandardQueryParameters(_messages.Message):
  """Query parameters accepted by all methods.

  Enums:
    FXgafvValueValuesEnum: V1 error format.
    AltValueValuesEnum: Data format for response.

  Fields:
    f__xgafv: V1 error format.
    access_token: OAuth access token.
    alt: Data format for response.
    bearer_token: OAuth bearer token.
    callback: JSONP
    fields: Selector specifying which fields to include in a partial response.
    key: API key. Your API key identifies your project and provides you with
      API access, quota, and reports. Required unless you provide an OAuth 2.0
      token.
    oauth_token: OAuth 2.0 token for the current user.
    pp: Pretty-print response.
    prettyPrint: Returns response with indentations and line breaks.
    quotaUser: Available to use for quota purposes for server-side
      applications. Can be any arbitrary string assigned to a user, but should
      not exceed 40 characters.
    trace: A tracing token of the form "token:<tokenid>" or "email:<ldap>" to
      include in api requests.
    uploadType: Legacy upload protocol for media (e.g. "media", "multipart").
    upload_protocol: Upload protocol for media (e.g. "raw", "multipart").
  """

  class AltValueValuesEnum(_messages.Enum):
    """Data format for response.

    Values:
      json: Responses with Content-Type of application/json
      media: Media download with context-dependent Content-Type
      proto: Responses with Content-Type of application/x-protobuf
    """
    json = 0
    media = 1
    proto = 2

  class FXgafvValueValuesEnum(_messages.Enum):
    """V1 error format.

    Values:
      _1: v1 error format
      _2: v2 error format
    """
    _1 = 0
    _2 = 1

  f__xgafv = _messages.EnumField('FXgafvValueValuesEnum', 1)
  access_token = _messages.StringField(2)
  alt = _messages.EnumField('AltValueValuesEnum', 3, default=u'json')
  bearer_token = _messages.StringField(4)
  callback = _messages.StringField(5)
  fields = _messages.StringField(6)
  key = _messages.StringField(7)
  oauth_token = _messages.StringField(8)
  pp = _messages.BooleanField(9, default=True)
  prettyPrint = _messages.BooleanField(10, default=True)
  quotaUser = _messages.StringField(11)
  trace = _messages.StringField(12)
  uploadType = _messages.StringField(13)
  upload_protocol = _messages.StringField(14)


class Status(_messages.Message):
  """The `Status` defines a logical error model that is suitable for different
  programming environments, including REST APIs and RPC APIs. It is used by
  [gRPC](https://github.com/grpc). The error model is designed to be:  -
  Simple to use and understand for most users. - Flexible enough to meet
  unexpected needs.  # Overview  The `Status` message contains 3 pieces of
  data: error code, error message, and error details. The error code should be
  an enum value of [google.rpc.Code][], but it may accept additional error
  codes if needed.  The error message should be a developer-facing English
  message that helps developers *understand* and *resolve* the error. If a
  localized user-facing error message is needed, it can be sent in the error
  details or localized by the client. The optional error details may contain
  arbitrary information about the error. There is a predefined set of error
  detail types in the package `google.rpc` which can be used for common error
  conditions.  # Language mapping  The `Status` message is the logical
  representation of the error model, but it is not necessarily the actual wire
  format. When the `Status` message is exposed in different client libraries
  and different wire protocols, it can be mapped differently. For example, it
  will likely be mapped to some exceptions in Java, but more likely mapped to
  some error codes in C.  # Other uses  The error model and the `Status`
  message can be used in a variety of environments - either with or without
  APIs - to provide consistent developer experience across different
  environments.  Example uses of this error model include:  - Partial errors.
  If a service needs to return partial errors to the client,     it may embed
  the `Status` in the normal response to indicate the partial     errors.  -
  Workflow errors. A typical workflow has multiple steps. Each step may
  have a `Status` message for error reporting purpose.  - Batch operations. If
  a client uses batch request and batch response, the     `Status` message
  should be used directly inside batch response, one for     each error sub-
  response.  - Asynchronous operations. If an API call embeds asynchronous
  operation     results in its response, the status of those operations should
  be     represented directly using the `Status` message.  - Logging. If some
  API errors are stored in logs, the message `Status` could     be used
  directly after any stripping needed for security/privacy reasons.

  Messages:
    DetailsValueListEntry: A DetailsValueListEntry object.

  Fields:
    code: The status code, which should be an enum value of
      [google.rpc.Code][].
    details: A list of messages that carry the error details.  There will be a
      common set of message types for APIs to use.
    message: A developer-facing error message, which should be in English. Any
      user-facing error message should be localized and sent in the
      [google.rpc.Status.details][google.rpc.Status.details] field, or
      localized by the client.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class DetailsValueListEntry(_messages.Message):
    """A DetailsValueListEntry object.

    Messages:
      AdditionalProperty: An additional property for a DetailsValueListEntry
        object.

    Fields:
      additionalProperties: Properties of the object. Contains field @ype with
        type URL.
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a DetailsValueListEntry object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  code = _messages.IntegerField(1, variant=_messages.Variant.INT32)
  details = _messages.MessageField('DetailsValueListEntry', 2, repeated=True)
  message = _messages.StringField(3)


class Trigger(_messages.Message):
  """Describes binding of computation to the event source.

  Fields:
    pubsub: A pub/sub type of source.
  """

  pubsub = _messages.MessageField('PubsubEventSource', 1)


encoding.AddCustomJsonEnumMapping(
    StandardQueryParameters.FXgafvValueValuesEnum, '_1', '1',
    package=u'apheleia')
encoding.AddCustomJsonEnumMapping(
    StandardQueryParameters.FXgafvValueValuesEnum, '_2', '2',
    package=u'apheleia')
encoding.AddCustomJsonFieldMapping(
    StandardQueryParameters, 'f__xgafv', '$.xgafv',
    package=u'apheleia')
